// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://ilcbdnphrscibduynydu.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6ImlsY2JkbnBocnNjaWJkdXlueWR1Iiwicm9sZSI6ImFub24iLCJpYXQiOjE3NDg0NjE2ODQsImV4cCI6MjA2NDAzNzY4NH0.IFeLQh8NNgTkWtEefbXwVog4kg1w1bayBVAKbGE6qu0";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);